apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: mysqld-exporter
  name: mysqld-exporter
  namespace: vaultdev-api
spec:
  endpoints:
  - interval: 30s
    port: https
    scheme: https
    path: /v1/sys/metrics
    # tlsConfig:
    #   ca:
    #     configMap:
    #       name: serving-certs-ca-bundle
    #       key: service-ca.crt
  selector:
    matchLabels:
      app: mysqld-exporter