apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: vaultdev-gcp
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access":"proxy",
                "editable": true,
                "name": "vault-prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.vaultdev-gcp.svc.cluster.local:8080",
                "version": 1
            },
            {
                "access":"proxy",
                "name": "oc-prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url: 'https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091",
                "editable": "true",
                "secureJsonData": {
                  "basicAuthPassword": "topsecret"
                },
                "jsonData": {
                  "timeInterval": "5s",
                  "tlsSkipVerify": "true"
                },
                "version": 1
            }
        ]
    }