# the following value have to be updated according before creating this config 
# customQuaryParameters -> namespace name to pull metrics from
# httpHeaderValue1 -> bearer authorization token value 
apiVersion: v1
kind: secret
metadata:
  name: grafana-datasources-secret
  namespace: vaultdev-gcp
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access":"proxy",
                "name": "vault-prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.vaultdev-gcp.svc.cluster.local:8080",
                "version": 1
            },
            {
                "access":"proxy",
                "name": "oc-prometheus",
                "orgId": 1,
                "type": "prometheus",
                "editable": true,
                "url": "https://thanos-querier-tenancy-openshift-monitoring.apps.pd120.caas.gcp.ford.com",
                "jsonData": {
                  "httpMethod": "GET",
                  "timeInterval": "5s",
                  "httpHeaderName1": "Authorization",
                  "customQueryParameters": "namespace=vaultdev-gcp"
                },
                "secureJsonData": {
                  "httpHeaderValue1": "Bearer xxxxxxxxx"
                },
                "version": 1
            }

        ]
    }