apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: vaultdev-gcp
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  sessionAffinity: None
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 9090
  selector:
    app.kubernetes.io/name: monitoring-statefulset
    
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: vaultdev-gcp
spec:
  sessionAffinity: None
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: monitoring-statefulset


kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: grafana-route
  #namespace: vault
  labels:
    app.kubernetes.io/name: monitoring-statefulset
  annotations:
    haproxy.router.openshift.io/rate-limit-connections: true
    haproxy.router.openshift.io/rate-limit-connections.rate-http: 50
spec:
  host: grafana-dev.app.ford.com
  to:
    kind: Service
    name: grafana-service
    weight: 100
  port:
    targetPort: 3000
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None