apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: vaultdev-gcp
data:
  prometheus.rules: |-
    groups:
    - name: demo-alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    # alerting:
    #   alertmanagers:
    #   - scheme: http
    #     static_configs:
    #     - targets:
    #       - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: vault-metrics
        metrics_path: /v1/sys/metrics
        authorization:
          credentials: {{xxxx}}
        params:
          format: ['prometheus']
        scheme: https
        tls_config:
          insecure_skip_verify: true
        static_configs:
          - targets: ['vault.vaultdev-gcp.svc.cluster.local:8200']   