apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: vaultdev-gcp
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  sessionAffinity: None
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 9090
  selector:
    app: prometheus-server