apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: vault
  name: vault-service-monitor
  namespace: vaultdev-gcp
spec:
  endpoints:
  - interval: 30s
    port: https
    scheme: https
    path: /v1/sys/metrics
    tlsConfig:
      ca:
        secret:
          name: vault-ca
          key: ca
  jobLabel: vault-metrics
  selector:
    matchLabels:
      app: vault